# The URL the site will be built for
base_url = "https://www.stevexciv.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# language
default_language = "en"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Atom/RSS
generate_feed = true
feed_filename = "rss.xml"
author = "Steve Troetti"

# set theme
theme = "tabi"

browser_theme_color = "#ec984f"

# homepage title
title = "Steve Troetti's Blog"

# enable tags
taxonomies = [{ name = "tags", feed = true }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
default_theme = "dark"
theme_switcher = false
skin = "lowcontrast_orange"
# navbar controls
menu = [
  { name = "blog", url = "blog", trailing_slash = true },
  # { name = "archive", url = "archive", trailing_slash = true },
  { name = "tags", url = "tags", trailing_slash = true },
  # TODO: re-enable projects once I decide what to showcase
  # { name = "projects", url = "projects", trailing_slash = true },
  # { name = "about", url = "about", trailing_slash = true },
]
# top-of-page, TOC, etc.
quick_navigation_buttons = true
# copy button on code examples
copy_button = true
# math
katex = true
# footer links (see https://welpo.github.io/tabi/blog/mastering-tabi-settings/#footer)
socials = [
  { name = "github", url = "https://github.com/SteveXCIV/", icon = "github" },
  { name = "linkedin", url = "https://www.linkedin.com/in/steve-troetti", icon = "linkedin" },
]
# RSS feed
feed_icon = true
# footer copyright
copyright = "© $CURRENT_YEAR Steve Troetti $SEPARATOR Unless otherwise noted, the content in this website is available under the [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license."
# put the site name _after_ the page name
invert_title_order = true
